global:
  smtp_from: '{{ .GMAIL_FROM }}'
  smtp_smarthost: 'smtp.gmail.com:587'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'  # default to telegram
  routes:
  - match:
      alertname: PrometheusRuleFailures
    group_interval: 5m
    repeat_interval: 30m
    receiver: 'webhook'
  - receiver: 'email'  # additional route for all alerts
  - receiver: 'telegram'  # ensure telegram gets all
inhibit_rules:
- source_matchers:
    - severity = critical
  target_matchers:
    - severity = warning
  equal:
    - alertname

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'telegram'
  telegram_configs:
  - bot_token: '{{ .TELEGRAM_BOT_TOKEN }}'
    chat_id: '{{ .TELEGRAM_CHAT_ID }}'
    parse_mode: 'HTML'

- name: 'email'
  email_configs:
  - to: '{{ .GMAIL_TO }}'
    from: '{{ .GMAIL_FROM }}'
    require_tls: true
    auth_username: '{{ .GMAIL_USER }}'
    auth_password: '{{ .GMAIL_APP_PASSWORD }}'