apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: true

- name: Elasticsearch
  type: elasticsearch
  access: proxy
  url: http://elasticsearch:9200
  database: "[logstash-]YYYY.MM.DD"
  jsonData:
    interval: Daily
    timeField: "@timestamp"
    esVersion: 80
    logMessageField: "message"
    logLevelField: "fields.level"
  isDefault: false
  editable: true

- name: Jaeger
  type: jaeger
  url: http://jaeger:16686
  access: proxy
  editable: true